# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=50, upload_to='banner/%Y/%m', verbose_name='banner\u56fe\u7247')),
                ('title', models.CharField(max_length=50, verbose_name='banner_title')),
                ('desc', models.CharField(max_length=30, verbose_name='banner\u63cf\u8ff0')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='desc',
            field=models.CharField(default='', max_length=50, verbose_name='blog\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(verbose_name='blog\u6587\u7ae0\u5185\u5bb9'),
        ),
    ]
